// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptskkevuykccrxpsozbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0c2trZXZ1eWtjY3J4cHNvemJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NTU0MjksImV4cCI6MjA1NTEzMTQyOX0.y9xW2EIDJ0Lh2agZyPZYctR9X-JKIgpBPKmA6hqnk9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);